tunnel: 511d9227-362c-49eb-a4a6-29fd2c49e9d7
credentials-file: "C:\Users\User\.cloudflared\511d9227-362c-49eb-a4a6-29fd2c49e9d7.json"

ingress:
  - hostname: lifebridge.online
    service: http://127.0.0.1:5000

  # Catch-all (must be last)
  - service: http_status:404
