# Netlify configuration for LifeBridge

[build]
  command = "pnpm run build:client"
  publish = "client/dist"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"
  PNPM_VERSION = "8"

[functions]
  node_bundler = "esbuild"

# ✅ Ensure static assets are served correctly
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/favicon.svg"
  to = "/favicon.svg"
  status = 200

# ✅ Proxy API requests to backend
[[redirects]]
  from = "/api/*"
  to = "https://api.lifebridge.online/:splat"
  status = 200
  force = true

# ✅ SPA fallback (routes → index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ------------------------
# 📦 Headers for caching + MIME types
# ------------------------

# Cache-busting for JS/CSS (hashed filenames)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# CSS served properly
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# SVG & images
[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000, immutable"
