# netlify.toml — LifeBridge (updated)
[build]
  # Install and build only the client (Netlify will build the frontend)
  command = "pnpm install --frozen-lockfile && pnpm run build:client"
  publish = "client/dist"

[build.environment]
  NODE_ENV = "production"
  # Use Node LTS for better compatibility on Netlify
  NODE_VERSION = "18"
  # Keep pnpm version if desired — Netlify will use pnpm if pnpm-lock.yaml exists
  PNPM_VERSION = "8"
  # Point the built client at the Render backend (working URL)
  VITE_API_URL = "https://real-time-organ-tracking-allocation.onrender.com"

[functions]
  node_bundler = "esbuild"

# Redirect API calls to the Render backend directly (Netlify proxies /api to Render)
[[redirects]]
  from = "/api/*"
  to = "https://real-time-organ-tracking-allocation.onrender.com/api/:splat"
  status = 200
  force = true

# React Router fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Static asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
