name = "lifebridge-cors-worker"
account_id = "82194f7ef88adc7d00ff879c47f5eb20"
compatibility_date = "2025-10-06"
workers_dev = true

# 👇 This is your built server file after running `pnpm run build`
main = "dist/server/index.js"

[build]
command = "pnpm run build"
