name = "lifebridge-cors-worker"
type = "javascript"

account_id = "82194f7ef88adc7d00ff879c47f5eb20"
workers_dev = true
compatibility_date = "2023-10-01"

[build]
command = "pnpm run build"

[deploy]
command = "npx wrangler deploy"
